package vista;

import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import negocio.m_venta;
import util.*;

public class venta_carro extends javax.swing.JFrame {
static DefaultComboBoxModel listModel=new DefaultComboBoxModel();
m_venta mv=new m_venta();

    public venta_carro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Interesado = new javax.swing.JButton();
        Interesado1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(40, 120, 190, 20);

        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(40, 50, 190, 20);

        jLabel2.setText("MARCA");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 20, 60, 14);

        jLabel3.setText("MODELO");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 90, 60, 14);

        jLabel4.setBackground(new java.awt.Color(255, 51, 102));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(145, 52, 108));
        jLabel4.setText("DESCRIPCIÓN");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 170, 110, 14);

        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(320, 40, 210, 40);

        jTextArea1.setBackground(new java.awt.Color(204, 153, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(40, 190, 260, 96);

        jLabel5.setBackground(new java.awt.Color(255, 255, 0));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 0));
        jLabel5.setText("SELECCIONAR");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(380, 20, 110, 14);

        jLabel6.setText("jLabel6");
        jLabel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(380, 130, 290, 210);

        Interesado.setText("Interesado");
        Interesado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InteresadoActionPerformed(evt);
            }
        });
        getContentPane().add(Interesado);
        Interesado.setBounds(50, 300, 100, 20);

        Interesado1.setText("TAZAR");
        Interesado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Interesado1ActionPerformed(evt);
            }
        });
        getContentPane().add(Interesado1);
        Interesado1.setBounds(50, 330, 100, 23);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bg_header_home.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setFocusCycleRoot(true);
        jLabel1.setFocusTraversalPolicyProvider(true);
        jLabel1.setFocusable(false);
        jLabel1.setRequestFocusEnabled(false);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 700, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
              DefaultComboBoxModel listModel1=new DefaultComboBoxModel();
        listModel1.removeAllElements();

        String x[][]=carro.getD();
        if(jComboBox2.getSelectedItem().toString().equals("Renoult")){

            for(int k=0;k<3;k++){
                if(x[k][0].equals("Renoult")){

                    listModel1.addElement(x[k][1]);
                    jComboBox1.setModel(listModel1);

                }

            }
        }
        else if (jComboBox2.getSelectedItem().toString().equals("Nissan")){

            for(int k=0;k<3;k++){
                if(x[k][0].equals("Nissan")){
                    listModel1.addElement(x[k][1]);
                    jComboBox1.setModel(listModel1);
                }
            }

        }

    }//GEN-LAST:event_jComboBox2ActionPerformed
DefaultListModel listModel2;
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
           // TODO add your handling code here:
        listModel2= new DefaultListModel();
        listModel2.removeAllElements();

        String x[][]=carro.getD();
        if(jComboBox1.getSelectedItem().toString().equals("Logan")){

            for(int k=0;k<carro.getM();k++){
                if(x[k][1].equals("Logan")){
                    listModel2.addElement(x[k][2]);
                    jList1.setModel(listModel2);

                }

            }
        }
        else if (jComboBox1.getSelectedItem().toString().equals("Fluences")){

            for(int k=0;k<carro.getM();k++){
                if(x[k][1].equals("Fluences")){
                    listModel2.addElement(x[k][2]);
                    jList1.setModel(listModel2);

                }
            }

        }

        else if (jComboBox1.getSelectedItem().toString().equals("Tidda")){

            for(int k=0;k<carro.getM();k++){
                if(x[k][1].equals("Tidda")){
                    listModel2.addElement(x[k][2]);
                    jList1.setModel(listModel2);

                }
            }

        }


    }//GEN-LAST:event_jComboBox1ActionPerformed
int cod=0;
    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        String x[][]=carro.getD();
        for(int i=0; i<x.length;i++){
             
            if (jList1.getSelectedValue().toString().equals(x[i][2])) {
                Icon icon =new ImageIcon(getClass().getResource("/Imagenes/"+i+".jpg"));
                jLabel6.setIcon(icon);
                jTextArea1.setText(x[i][2]);
                cod=i;
                

        }
        }

    
        listModel2 = new DefaultListModel();
        jList1.setModel(listModel2);

    }//GEN-LAST:event_jList1ValueChanged
int i=0;
    private void InteresadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InteresadoActionPerformed
         confirma re=new confirma();
           re.setVisible(true);  
           i=carro.getL();
           re.jLabel4.setText(String.valueOf(cod));
           mv.venta_producto(i,cod, re.jPasswordField1.getText());
           i++;
           carro.setL(i);
           
    }//GEN-LAST:event_InteresadoActionPerformed

    private void Interesado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Interesado1ActionPerformed
        // TODO add your handling code here:
           Tazar re=new Tazar();
           re.setVisible(true);  
         
           
    }//GEN-LAST:event_Interesado1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(venta_carro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(venta_carro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(venta_carro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(venta_carro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new venta_carro().setVisible(true);
                carro.data_carros(); 
                     //llenado del combobox
                String x[][]=carro.getD();
                
             for(int i=0;i<3;i++){
                 
                 listModel.addElement(x[i][0]);
                
                jComboBox2.setModel(listModel);
                
            }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Interesado;
    private javax.swing.JButton Interesado1;
    private javax.swing.JComboBox jComboBox1;
    private static javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
